from Clases_importadas.Desarrollo import *

Lucía = Niño('Lucía', 'Carmona', 10, 'Femenino')
Lucía.características()
Lucía.modificarpeso(29)
David = Niño('David', 'Carmona', 45, 'Varón')
David.características()
David.modificarpeso(79)
Marcos = Persona('Marcos', 'Carmona', 48, 'Varón')
Marcos.características()
Marcos.modificarpeso(90)
Marcos.características()
print (Lucía.sexo)
print (Lucía.sexo)
David.características()